Repository LIKELION-GOREADY/GOREADY_BE, pull requests merged in 2024-11, with the labels that each got.

#13 [Add/#12] Redis 구축
  build.gradle
  src/main/java/com/example/goready/dto/Address.java
  src/main/java/com/example/goready/global/config/RedisConfig.java
  src/main/java/com/example/goready/global/exception/GlobalException.java
  src/main/java/com/example/goready/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/goready/global/response/ApiResponse.java
  src/main/java/com/example/goready/global/response/status/ErrorStatus.java
  src/main/java/com/example/goready/global/response/status/SuccessStatus.java
  src/main/java/com/example/goready/utils/AddressUtil.java
  src/main/java/com/example/goready/utils/RedisUtil.java
  src/test/java/com/example/goready/utils/AddressUtilTest.java
  src/test/java/com/example/goready/utils/RedisUtilTest.java
Labels: add

#14 [Feat/#11] 미세먼지 조회 기능 구현
  build.gradle
  src/main/java/com/example/goready/controller/MaskController.java
  src/main/java/com/example/goready/converter/MaskConverter.java
  src/main/java/com/example/goready/dto/MaskResponse.java
  src/main/java/com/example/goready/global/config/WebConfig.java
  src/main/java/com/example/goready/global/response/status/ErrorStatus.java
  src/main/java/com/example/goready/service/mask/MaskService.java
  src/main/java/com/example/goready/utils/AddressUtil.java
  src/test/java/com/example/goready/utils/AddressUtilTest.java
Labels: feat

#16 feat : cors 설정
  src/main/java/com/example/goready/global/config/WebConfig.java
Labels: feat

#17 Feat/#8
  src/main/java/com/example/goready/controller/WeatherController.java
  src/main/java/com/example/goready/controller/convertTestController.java
  src/main/java/com/example/goready/converter/WeatherConverter.java
  src/main/java/com/example/goready/dto/LonXLatY.java
  src/main/java/com/example/goready/dto/WeatherData.java
  src/main/java/com/example/goready/dto/WeatherResponse.java
  src/main/java/com/example/goready/global/response/status/ErrorStatus.java
  src/main/java/com/example/goready/global/response/status/SuccessStatus.java
  src/main/java/com/example/goready/service/temperature/TemperatureService.java
  src/main/java/com/example/goready/service/umbrella/UmbrellaService.java
  src/main/java/com/example/goready/service/weather/WeatherApiService.java
  src/main/java/com/example/goready/service/weather/WeatherService.java
  src/main/java/com/example/goready/service/weatherApi/WeatherApiService.java
  src/main/java/com/example/goready/utils/GridUtils.java
  src/main/java/com/example/goready/utils/LonXLatY.java
  src/main/java/com/example/goready/utils/RedisUtil.java
Labels: feat

#21 [Fix/#20] : WeatherData에 json 생성자 추가
  src/main/java/com/example/goready/dto/WeatherData.java
Labels: fix

#25 refactor/#24 날씨조회기능 비동기적 처리
  src/main/java/com/example/goready/controller/WeatherController.java
  src/main/java/com/example/goready/service/weather/WeatherApiService.java
  src/main/java/com/example/goready/service/weather/WeatherService.java
Labels: refactor

#27 fix/#26 어제 날씨 조회 에러 해결
  src/main/java/com/example/goready/service/weather/WeatherApiService.java
Labels: fix
